import type { TeamMember } from '../entities/team/model/team';

export const team: TeamMember[] = [
    {
        id: 'u1',
        name: 'Alex Morgan',
        role: 'Frontend Engineer',
        timezoneOffset: -5,
        availability: 'available',
        skills: ['React', 'TypeScript', 'Accessibility', 'CSS'],
    },
    {
        id: 'u2',
        name: 'Priya Nair',
        role: 'Backend Engineer',
        timezoneOffset: 5.5,
        availability: 'focus',
        skills: ['Node.js', 'PostgreSQL', 'API Design'],
    },
    {
        id: 'u3',
        name: 'Luca Bianchi',
        role: 'Product Designer',
        timezoneOffset: 1,
        availability: 'in_meeting',
        skills: ['Figma', 'UX Research', 'Design Systems'],
    },
    {
        id: 'u4',
        name: 'Emily Chen',
        role: 'QA Engineer',
        timezoneOffset: 8,
        availability: 'available',
        skills: ['Playwright', 'Test Automation', 'Regression Testing'],
    },
    {
        id: 'u5',
        name: 'Mateo Alvarez',
        role: 'Frontend Engineer',
        timezoneOffset: -3,
        availability: 'offline',
        skills: ['Vue', 'JavaScript', 'SCSS'],
    },
    {
        id: 'u6',
        name: 'Sara Lindholm',
        role: 'Product Manager',
        timezoneOffset: 1,
        availability: 'available',
        skills: ['Roadmapping', 'Stakeholder Management', 'Agile'],
    },
    {
        id: 'u7',
        name: 'Daniel Okafor',
        role: 'Backend Engineer',
        timezoneOffset: 1,
        availability: 'focus',
        skills: ['Java', 'Spring', 'System Design'],
    },
    {
        id: 'u8',
        name: 'Hannah Wilson',
        role: 'UX Writer',
        timezoneOffset: 0,
        availability: 'available',
        skills: ['Microcopy', 'Content Design', 'Accessibility'],
    },
    {
        id: 'u9',
        name: 'Kenji Sato',
        role: 'DevOps Engineer',
        timezoneOffset: 9,
        availability: 'in_meeting',
        skills: ['AWS', 'CI/CD', 'Docker', 'Monitoring'],
    },
    {
        id: 'u10',
        name: 'Olivia Brown',
        role: 'Frontend Engineer',
        timezoneOffset: -8,
        availability: 'focus',
        skills: ['React', 'Performance', 'Web Animations'],
    },
    {
        id: 'u11',
        name: 'Thomas Müller',
        role: 'Engineering Manager',
        timezoneOffset: 1,
        availability: 'available',
        skills: ['Team Leadership', 'Architecture', 'Hiring'],
    },
    {
        id: 'u12',
        name: 'Aisha Rahman',
        role: 'Data Analyst',
        timezoneOffset: 6,
        availability: 'offline',
        skills: ['SQL', 'Data Visualization', 'Analytics'],
    },
    {
        id: 'u13',
        name: 'Noah Peterson',
        role: 'QA Engineer',
        timezoneOffset: -6,
        availability: 'available',
        skills: ['Manual Testing', 'Bug Reporting', 'Test Cases'],
    },
    {
        id: 'u14',
        name: 'Isabella Rossi',
        role: 'Product Designer',
        timezoneOffset: 1,
        availability: 'focus',
        skills: ['UI Design', 'Prototyping', 'User Testing'],
    },
    {
        id: 'u15',
        name: 'Victor Nguyen',
        role: 'Backend Engineer',
        timezoneOffset: 7,
        availability: 'available',
        skills: ['Go', 'Distributed Systems', 'gRPC'],
    },
    {
        id: 'u16',
        name: 'Sophie Dubois',
        role: 'UX Researcher',
        timezoneOffset: 1,
        availability: 'in_meeting',
        skills: ['User Interviews', 'Usability Testing'],
    },
    {
        id: 'u17',
        name: "James O'Connor",
        role: 'Security Engineer',
        timezoneOffset: 0,
        availability: 'focus',
        skills: ['AppSec', 'Threat Modeling', 'OWASP'],
    },
    {
        id: 'u18',
        name: 'María Gómez',
        role: 'Customer Support Lead',
        timezoneOffset: -3,
        availability: 'available',
        skills: ['Support Ops', 'Knowledge Base', 'Communication'],
    },
    {
        id: 'u19',
        name: 'Ethan Park',
        role: 'Mobile Engineer',
        timezoneOffset: 9,
        availability: 'offline',
        skills: ['React Native', 'iOS', 'Android'],
    },
    {
        id: 'u20',
        name: 'Nina Kowalska',
        role: 'Frontend Engineer',
        timezoneOffset: 1,
        availability: 'available',
        skills: ['Angular', 'TypeScript', 'Design Systems'],
    },
];
